### ISSUE TITLE
It requires downgrade to ppx_deriving 2.2

### ISSUE THREAD

**Issue by artemkin** [whitequark/ppx_deriving_protobuf#11]
So, basically, it can't be used with ppx_deriving 3.0. Is this intended?

**Comment by whitequark** [comment]
Not really; I will update the dependencies shortly.

**Comment by whitequark** [comment]
https://github.com/ocaml/opam-repository/pull/5246

**Comment by whitequark** [comment]
Done.

**Comment by artemkin** [comment]
Thanks
