### ISSUE TITLE
Discussion: Support in NPM for JavaScript support

### ISSUE THREAD

**Issue by mransan** [whitequark/ppx_deriving_protobuf#16]
In an effort to use [ocaml-protoc](https://github.com/mransan/ocaml-protoc) in JavaScript, I would like to publish ppx_deriving_protobuf to NPM.

This essentially consist in 2 files:
* `bsconfig.json`: Build instruction for BuckleScript
* `package.json`: Package specification for the NPM package

This issue is just for awareness, I am happy maintaining a fork which contains the NPM setup.

**Comment by whitequark** [comment]
Sure, send a PR.

**Comment by mransan** [comment]
@whitequark will do. Thanks a lot
